# Generated by Django 4.0.5 on 2022-07-01 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_categories_name_articles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['-time_create', 'title']},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['-priority', '-time_create']},
        ),
    ]
