name: Deploy

on:
  push:
    branches:
      - master
    
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploying
      uses: appleboy/ssh-action@master
      with:
        host: 91.227.18.41
        username: bbam_ru
        key: ${{ secrets.DEPLOY_SERVER_KEY }}
        port: 22
        script: |
          cd django_learning_coolsite
          git reset --hard
          git pull origin master
          cd ..
          venv/bin/python -m pip install -r django_learning_coolsite/requirements.txt
          pm2 delete bbam_ru
          pm2 start bbam.json
          pm2 save --force
