name: Deploy

on:
  push:
    branches:
      - master
    
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploying
      uses: appleboy/ssh-action@master
      with:
        host: 91.227.18.41
        username: bbam_ru
        key: ${{ secrets.DEPLOY_SERVER_KEY }}
        port: 22
        script: |
          cd django_learning_coolsite
          git reset --hard
          git pull origin master
          cd ..
          venv/bin/python -m pip install -r django_learning_coolsite/requirements.txt
          pm2 delete bbam_ru
          pm2 start bbam.json
          pm2 save --force
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        db: [ postgres ]
        python-version: [ "3.10" ]
        include:
          - db: postgres
            db_user: runner
            db_password: ''
            db_host: 127.0.0.1
            db_port: 5432
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Start PostgreSQL
        run: |
          sudo systemctl start postgresql.service
          sudo -u postgres createuser -s runner
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install braintree mysqlclient apprise
      - name: Run Tests
        env:
          SECRET_KEY: ${{secrets.SECRET_KEY}}
          DB_NAME: ${{ matrix.db }}
          DB_USER: ${{ matrix.db_user }}
          DB_HOST: ${{ matrix.db_host }}
          DB_PORT: ${{ matrix.db_port }}
          DB_PASSWORD: ${{ matrix.db_password }}
        run: |
          python manage.py test
