name: Deploy

on:
  push:
    branches: [ master ]
    
jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploying
      uses: appleboy/ssh-action@master
      with:
        host: 91.227.18.41
        username: bbam_ru
        key: ${{ secrets.DEPLOY_SERVER_KEY }}
        port: 22
        script: |
          cd django_learning_coolsite
          git pull origin master
          cat requirements.txt | xargs -n 1 pip install
          cd ..
          pm2 delete bbam_ru
          pm2 start bbam.json
          pm2 save
